version: '3.5'
services:
  annuaire-dev:
    container_name: annuaire-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
